In [ ]:
import os 
import pandas as pd 
import numpy as np

file_path="/home/u00926/Huang"

In [ ]:
train_X=pd.read_excel(file_path+"/train_X.xlsx",sheet_name = None, engine = "openpyxl")
train_y=pd.read_excel(file_path+"/train_y.xlsx",sheet_name = None, engine = "openpyxl")
valid_X=pd.read_excel(file_path+"/valid_X.xlsx",sheet_name = None, engine = "openpyxl")
valid_y=pd.read_excel(file_path+"/valid_y.xlsx",sheet_name = None, engine = "openpyxl")

In [3]:
train_X['市場データ_final'].head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,データ種類,リターン,リターン,リターン,リターン,リターン,リターン,リターン,リターン,リターン,...,原数値,原数値,リターン,リターン,リターン,リターン,リターン,原数値,原数値,原数値
2,設定すべきラグ日数,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,カテゴリ,目的変数関連,目的変数関連,目的変数関連,主要指数,主要指数,主要指数,主要指数,主要指数,主要指数,...,為替系,為替系,商品系,商品系,商品系,商品系,商品系,商品系,商品系,その他
4,NaN,米国株（先物）,米国債（先物）,株40債券60ポート,日本株（先物）,日本債（先物）,欧州株（先物）,欧州債（先物）,香港株（先物）,EM株（指数）,...,USD/TRY,USD/BRL,ICEブレント原油（先物）,CMX金（先物）,銀（先物）,CMX銅（先物）,CME材木（先物）,バルチック海運指数,ビットコイン,VIX
5,Dates,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,HIIndex,MXEFIndex,...,TRYCurncy,BRLCurncy,COComdty,GCComdty,SIComdty,HGComdty,LBComdty,BDIYindex,XBTCurncy,VIXIndex
6,1999-04-01 00:00:00,0.007346,-0.001362,0.002121,0.036825,0.001509,0.009022,-0.000526,0.02157,0.001105,...,0.373,1.725,-0.034121,0.000355,0.01167,0.001594,-0.010963,891,NaN,22.06
7,1999-04-02 00:00:00,0,0.00573,0.003438,0.002449,-0.001432,0,0,0,0.010683,...,0.3754,1.725,0,0,0,0,0,891,NaN,NaN
8,1999-04-05 00:00:00,0.023604,0.000543,0.009767,0.000611,-0.001207,0,0,0,0.002008,...,0.3761,1.7375,0,-0.006028,-0.021877,0.002387,-0.017376,891,NaN,22.19
9,1999-04-06 00:00:00,-0.00225,0.004067,0.00154,0.004274,-0.002569,0.025426,0.010093,0,0.009576,...,0.376,1.7325,0.014266,0.005351,0.0061,-0.003968,-0.01372,883,NaN,22.65

In [4]:
train_X['経済指標データ_final'].head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,データ種類,原数値,原数値,原数値,原数値,原数値,原数値,原数値,原数値,原数値,...,原数値,原数値,原数値,原数値,原数値,原数値,原数値,原数値,原数値,原数値
2,設定すべきラグ日数,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,カテゴリ,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,...,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標,経済指標
4,NaN,製造業ISM 総合指数,製造業ISM 新規受注,製造業ISM 生産,製造業ISM 入荷遅延,製造業ISM 雇用,製造業ISM 在庫,製造業ISM 受注残,製造業ISM 輸出,製造業ISM 輸入,...,非製造業ISM 輸入,民間住宅着工件数合計 季調値,民間住宅建設許可件数合計 季調値,米国中古住宅販売\n季調値,新築一戸建住宅販売件数合計\n季調値,フィラデルフィア連銀 景気動向指数,エンパイアステート製造調査 一般景況感 季調済,シカゴ購買部協会景気指数\n季調値,コンファレンスボード 消費者信頼感\n季調値,ミシガン大学消費者 マインド指数
5,Dates,NAPMPMIIndex,NAPMNEWOIndex,NAPMPRODIndex,NAPMSUPLIndex,NAPMEMPLIndex,NAPMINVIndex,NAPMBACKIndex,NAPMEXPTIndex,NAPMIMPTIndex,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
6,1997-03-31 00:00:00,53.1,57.6,58.9,52.1,45.9,41.3,48.5,54.6,53.7,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
7,1997-04-01 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
8,1997-04-02 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
9,1997-04-03 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100

In [5]:
train_y['Sheet1']

          Dates  dec_rate  signal
0    1999-04-01 -0.004176       0
1    1999-04-02 -0.002029       0
2    1999-04-05 -0.006016       0
3    1999-04-06 -0.008308       0
4    1999-04-07  0.000000       0
...         ...       ...     ...
4627 2016-12-26 -0.000217       0
4628 2016-12-27 -0.000683       0
4629 2016-12-28 -0.001023       0
4630 2016-12-29 -0.000561       0
4631 2016-12-30 -0.001239       0

[4632 rows x 3 columns]

train_Xの市場データと経済指標を分離する

In [6]:
train_mkt_data=train_X['市場データ_final']
train_ind_data=train_X['経済指標データ_final']

市場データにおいて、数値とインデックスを分ける

In [7]:
temp=train_mkt_data.iloc[6:]
temp.columns=list(train_mkt_data.iloc[5])
temp

,Dates,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,HIIndex,MXEFIndex,...,TRYCurncy,BRLCurncy,COComdty,GCComdty,SIComdty,HGComdty,LBComdty,BDIYindex,XBTCurncy,VIXIndex
6,1999-04-01 00:00:00,0.007346,-0.001362,0.002121,0.036825,0.001509,0.009022,-0.000526,0.02157,0.001105,...,0.373,1.725,-0.034121,0.000355,0.01167,0.001594,-0.010963,891,NaN,22.06
7,1999-04-02 00:00:00,0,0.00573,0.003438,0.002449,-0.001432,0,0,0,0.010683,...,0.3754,1.725,0,0,0,0,0,891,NaN,NaN
8,1999-04-05 00:00:00,0.023604,0.000543,0.009767,0.000611,-0.001207,0,0,0,0.002008,...,0.3761,1.7375,0,-0.006028,-0.021877,0.002387,-0.017376,891,NaN,22.19
9,1999-04-06 00:00:00,-0.00225,0.004067,0.00154,0.004274,-0.002569,0.025426,0.010093,0,0.009576,...,0.376,1.7325,0.014266,0.005351,0.0061,-0.003968,-0.01372,883,NaN,22.65
10,1999-04-07 00:00:00,0.006013,-0.00081,0.001919,0.00304,0.006212,-0.008174,-0.000521,0.050764,0.010974,...,0.3761,1.7325,-0.038848,0.001774,0.002425,0.030279,0.004328,873,NaN,22.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4633,2016-12-26 00:00:00,0,0,0,-0.002066,-0.000467,0,0,0,0.00101,...,3.5123,3.28,0,0,0,0,0,961,898.25,NaN
4634,2016-12-27 00:00:00,0.000442,-0.001267,-0.000583,0,0,0.002145,0.002994,0,0.002623,...,3.5215,3.2725,0.016637,0.004587,0.014595,0.014724,-0.007219,961,931.73,11.99
4635,2016-12-28 00:00:00,-0.006966,0.003551,-0.000656,0.005694,0.000868,-0.000612,-0.000609,0.008497,0.007719,...,3.5402,3.2769,0.002288,0.001844,0.003065,-0.005963,0.019602,961,967.36,12.95
4636,2016-12-29 00:00:00,-0.000111,0.002401,0.001396,-0.018528,0.002067,-0.002142,0.003353,0.002669,0.008529,...,3.5239,3.2539,-0.001931,0.015076,0.011223,-0.004999,0.006202,961,968.09,13.37
4637,2016-12-30 00:00:00,-0.003898,0.002774,0.000105,0.001573,-0.000067,0.004906,-0.002734,0.00794,0.004462,...,3.5235,3.25,-0.000528,-0.005526,-0.01412,0.007034,0.0151,961,952.01,14.04

要らないデータの削除

In [8]:
#金利3年を削除リストに
eliminate_list = ("USGG3YRIndex","USYC2Y3YIndex","USYC3Y5YIndex","USYC3Y7YIndex","USYC3Y10Index","USYC3Y20Index","USYC3Y30Index","BF020305Index","BF020307Index","BF020310Index","BF020320Index","BF020330Index","BF030507Index","BF030510Index","BF030520Index","BF030530Index","BF030710Index","BF030720Index","BF030730Index","BF031020Index","BF031030Index")
eliminate_num_list = []
for j in range(len(train_mkt_data.columns)):
    if train_mkt_data.iloc[5,j] in eliminate_list:
        eliminate_num_list.append('Unnamed: '+str(j))

In [9]:
#全部Nanの列を削除リストに：もしこの列のすべての値はNanのならこの列を削除する
for i in range(len(temp.columns)):
    if temp.isnull().all()[i] == True:
        eliminate_num_list.append('Unnamed: '+str(i))
eliminate_num_list

['Unnamed: 31',
 'Unnamed: 37',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 29',
 'Unnamed: 35',
 'Unnamed: 41',
 'Unnamed: 46',
 'Unnamed: 50',
 'Unnamed: 53',
 'Unnamed: 55',
 'Unnamed: 57',
 'Unnamed: 61',
 'Unnamed: 65',
 'Unnamed: 68',
 'Unnamed: 70',
 'Unnamed: 74',
 'Unnamed: 77',
 'Unnamed: 79',
 'Unnamed: 82',
 'Unnamed: 84',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 89',
 'Unnamed: 90']

In [10]:
train_mkt_data=train_mkt_data.drop(eliminate_num_list,axis=1)
train_mkt_data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,データ種類,リターン,リターン,リターン,リターン,リターン,リターン,リターン,リターン,リターン,...,原数値,原数値,リターン,リターン,リターン,リターン,リターン,原数値,原数値,原数値
2,設定すべきラグ日数,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,カテゴリ,目的変数関連,目的変数関連,目的変数関連,主要指数,主要指数,主要指数,主要指数,主要指数,主要指数,...,為替系,為替系,商品系,商品系,商品系,商品系,商品系,商品系,商品系,その他
4,NaN,米国株（先物）,米国債（先物）,株40債券60ポート,日本株（先物）,日本債（先物）,欧州株（先物）,欧州債（先物）,香港株（先物）,EM株（指数）,...,USD/TRY,USD/BRL,ICEブレント原油（先物）,CMX金（先物）,銀（先物）,CMX銅（先物）,CME材木（先物）,バルチック海運指数,ビットコイン,VIX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4633,2016-12-26 00:00:00,0,0,0,-0.002066,-0.000467,0,0,0,0.00101,...,3.5123,3.28,0,0,0,0,0,961,898.25,NaN
4634,2016-12-27 00:00:00,0.000442,-0.001267,-0.000583,0,0,0.002145,0.002994,0,0.002623,...,3.5215,3.2725,0.016637,0.004587,0.014595,0.014724,-0.007219,961,931.73,11.99
4635,2016-12-28 00:00:00,-0.006966,0.003551,-0.000656,0.005694,0.000868,-0.000612,-0.000609,0.008497,0.007719,...,3.5402,3.2769,0.002288,0.001844,0.003065,-0.005963,0.019602,961,967.36,12.95
4636,2016-12-29 00:00:00,-0.000111,0.002401,0.001396,-0.018528,0.002067,-0.002142,0.003353,0.002669,0.008529,...,3.5239,3.2539,-0.001931,0.015076,0.011223,-0.004999,0.006202,961,968.09,13.37
4637,2016-12-30 00:00:00,-0.003898,0.002774,0.000105,0.001573,-0.000067,0.004906,-0.002734,0.00794,0.004462,...,3.5235,3.25,-0.000528,-0.005526,-0.01412,0.007034,0.0151,961,952.01,14.04

経済指標データに対する点検を行う

In [11]:
temp2 = train_ind_data.loc[6:]
temp2.columns = list(train_ind_data.iloc[5])
temp2

,Dates,NAPMPMIIndex,NAPMNEWOIndex,NAPMPRODIndex,NAPMSUPLIndex,NAPMEMPLIndex,NAPMINVIndex,NAPMBACKIndex,NAPMEXPTIndex,NAPMIMPTIndex,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
6,1997-03-31 00:00:00,53.1,57.6,58.9,52.1,45.9,41.3,48.5,54.6,53.7,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
7,1997-04-01 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
8,1997-04-02 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
9,1997-04-03 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
10,1997-04-04 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5156,2016-12-26 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,57.6,107.1,98.2
5157,2016-12-27 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
5158,2016-12-28 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
5159,2016-12-29 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
5160,2016-12-30 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2

市場データのインデックスを処理する
処理後：各指標名は縦に並んで、指標名は各行のインデックスになり、指標名の属性は各列のインデックスになる。このdfは各指標名の具体的な内容を説明する

In [12]:
train_mkt_info=train_mkt_data.loc[:5].T.copy() #この時、各指標の名前は縦方向に並んで、縦軸のインデックスはunnamed0～107
train_mkt_info.columns=list(train_mkt_info.iloc[0])
train_mkt_info.drop(train_mkt_info.index[0],inplace=True)
train_mkt_info.index=list(train_mkt_info['Dates'])#字母名前で表すの指標名を今行のインデックスにする
train_mkt_info.drop(columns="Dates", inplace=True)#dfから字母指標名を削除(もうインデックスになったため）
train_mkt_info.rename(columns = {np.nan:"補足"}, inplace=True)
train_mkt_info

                     補足 データ種類 設定すべきラグ日数    カテゴリ          補足
ESIndex             NaN  リターン         0  目的変数関連     米国株（先物）
TYComdty            NaN  リターン         0  目的変数関連     米国債（先物）
TargetPortDailyRtn  NaN  リターン         0  目的変数関連  株40債券60ポート
NKIndex             NaN  リターン         0    主要指数     日本株（先物）
JBComdty            NaN  リターン         0    主要指数     日本債（先物）
...                 ...   ...       ...     ...         ...
HGComdty            NaN  リターン         0     商品系    CMX銅（先物）
LBComdty            NaN  リターン         0     商品系   CME材木（先物）
BDIYindex           NaN   原数値         0     商品系   バルチック海運指数
XBTCurncy           NaN   原数値         0     商品系      ビットコイン
VIXIndex            NaN   原数値         0     その他         VIX

[70 rows x 5 columns]

経済指標データのインデックスも同様に処理する

In [13]:
train_ind_info = train_ind_data.loc[:5].T.copy()
train_ind_info.columns = list(train_ind_info.iloc[0])
train_ind_info.drop(train_ind_info.index[0], inplace=True)
train_ind_info.index = list(train_ind_info["Dates"])
train_ind_info.drop(columns="Dates", inplace=True)
train_ind_info.rename(columns = {np.nan:"補足"}, inplace=True)
train_ind_info

                補足 データ種類 設定すべきラグ日数  カテゴリ                         補足
NAPMPMIIndex   NaN   原数値         0  経済指標                製造業ISM 総合指数
NAPMNEWOIndex  NaN   原数値         0  経済指標                製造業ISM 新規受注
NAPMPRODIndex  NaN   原数値         0  経済指標                  製造業ISM 生産
NAPMSUPLIndex  NaN   原数値         0  経済指標                製造業ISM 入荷遅延
NAPMEMPLIndex  NaN   原数値         0  経済指標                  製造業ISM 雇用
NAPMINVIndex   NaN   原数値         0  経済指標                  製造業ISM 在庫
NAPMBACKIndex  NaN   原数値         0  経済指標                 製造業ISM 受注残
NAPMEXPTIndex  NaN   原数値         0  経済指標                  製造業ISM 輸出
NAPMIMPTIndex  NaN   原数値         0  経済指標                  製造業ISM 輸入
NAPMNMIIndex   NaN   原数値         0  経済指標               非製造業ISM 総合指数
NAPMNMANIndex  NaN   原数値         0  経済指標  非製造業ISM Business Activity
NAPMNNOIndex   NaN   原数値         0  経済指標               非製造業ISM 新規受注
NAPMNEMPIndex  NaN   原数値         0  経済指標                 非製造業ISM 雇用
NAPMNSDIndex   NaN   原数値         0  経済指標               非製造業ISM 入荷遅延
NAPMNISIndex   NaN   原数値         0  経済指標                 非製造業ISM 在庫
NAPMNNEOIndex  NaN   原数値         0  経済指標                 非製造業ISM 輸出
NAPMNIMPIndex  NaN   原数値         0  経済指標                 非製造業ISM 輸入
NHSPSTOTIndex  NaN   原数値         0  経済指標             民間住宅着工件数合計 季調値
NHSPATOTIndex  NaN   原数値         0  経済指標           民間住宅建設許可件数合計 季調値
ETSLTOTLIndex  NaN   原数値         0  経済指標              米国中古住宅販売\n季調値
NHSLTOTIndex   NaN   原数値         0  経済指標         新築一戸建住宅販売件数合計\n季調値
OUTFGAFIndex   NaN   原数値         0  経済指標          フィラデルフィア連銀 景気動向指数
EMPRGBCIIndex  NaN   原数値         0  経済指標    エンパイアステート製造調査 一般景況感 季調済
CHPMINDXIndex  NaN   原数値         0  経済指標          シカゴ購買部協会景気指数\n季調値
CONCCONFIndex  NaN   原数値         0  経済指標     コンファレンスボード 消費者信頼感\n季調値
CONSSENTIndex  NaN   原数値         0  経済指標           ミシガン大学消費者 マインド指数

指標データの値をdfとして抽出し、字母の指標名を列のインデックスにして、行のインデックスを０からと再設定する

In [14]:
train_mkt_data = train_mkt_data.loc[5:].copy()
train_mkt_data.columns = list(train_mkt_data.iloc[0])
train_mkt_data.drop(index=5, inplace=True)
train_mkt_data.reset_index(inplace=True, drop=True)
train_mkt_data.head(5)

,Dates,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,HIIndex,MXEFIndex,...,TRYCurncy,BRLCurncy,COComdty,GCComdty,SIComdty,HGComdty,LBComdty,BDIYindex,XBTCurncy,VIXIndex
0,1999-04-01 00:00:00,0.007346,-0.001362,0.002121,0.036825,0.001509,0.009022,-0.000526,0.02157,0.001105,...,0.373,1.725,-0.034121,0.000355,0.01167,0.001594,-0.010963,891,NaN,22.06
1,1999-04-02 00:00:00,0,0.00573,0.003438,0.002449,-0.001432,0,0,0,0.010683,...,0.3754,1.725,0,0,0,0,0,891,NaN,NaN
2,1999-04-05 00:00:00,0.023604,0.000543,0.009767,0.000611,-0.001207,0,0,0,0.002008,...,0.3761,1.7375,0,-0.006028,-0.021877,0.002387,-0.017376,891,NaN,22.19
3,1999-04-06 00:00:00,-0.00225,0.004067,0.00154,0.004274,-0.002569,0.025426,0.010093,0,0.009576,...,0.376,1.7325,0.014266,0.005351,0.0061,-0.003968,-0.01372,883,NaN,22.65
4,1999-04-07 00:00:00,0.006013,-0.00081,0.001919,0.00304,0.006212,-0.008174,-0.000521,0.050764,0.010974,...,0.3761,1.7325,-0.038848,0.001774,0.002425,0.030279,0.004328,873,NaN,22.81

In [15]:
train_mkt_data.columns

Index(['Dates', 'ESIndex', 'TYComdty', 'TargetPortDailyRtn', 'NKIndex',
       'JBComdty', 'VGIndex', 'RXComdty', 'HIIndex', 'MXEFIndex',
       'LUACTRUUIndex', 'LUACTRJHIndex', 'LCA3TRUUIndex', 'LCA2TRUUIndex',
       'LCA1TRUUIndex', 'LCB1TRUUIndex', 'BCBATRUUIndex', 'BCBHTRUUIndex',
       'EMUSTRUUIndex', 'XLKEquity', 'XLFEquity', 'XLVEquity', 'XLEEquity',
       'XLYEquity', 'XLPEquity', 'XLIEquity', 'XLUEquity', 'XLBEquity',
       'XLREEquity', 'USGG2YRIndex', 'USGG5YRIndex', 'USGG7YRIndex',
       'USGG10YRIndex', 'USGG30YRIndex', 'USYC2Y5YIndex', 'USYC2Y7YIndex',
       'USYC2Y10Index', 'USYC2Y30Index', 'USYC5Y7YIndex', 'USYC5Y10Index',
       'USYC5Y30Index', 'USYC7Y10Index', 'USYC7Y30Index', 'USYC1030Index',
       'BF020507Index', 'BF020510Index', 'BF020530Index', 'BF020710Index',
       'BF020730Index', 'BF021030Index', 'BF050710Index', 'BF050730Index',
       'BF051030Index', 'BF071030Index', 'DXYCurncy', 'JPYCurncy', 'EURCurncy',
       'GBPCurncy', 'AUDCurncy', 'CADCurncy', 'CNYCurncy', 'TRYCurncy',
       'BRLCurncy', 'COComdty', 'GCComdty', 'SIComdty', 'HGComdty', 'LBComdty',
       'BDIYindex', 'XBTCurncy', 'VIXIndex'],
      dtype='object')

経済指標データに対しても同様に処理する

In [16]:
train_ind_data =train_ind_data.loc[5:].copy()
train_ind_data.columns = list(train_ind_data.iloc[0])
train_ind_data.drop(index=5, inplace=True)
train_ind_data.reset_index(inplace=True, drop=True)
train_ind_data.head(5)

,Dates,NAPMPMIIndex,NAPMNEWOIndex,NAPMPRODIndex,NAPMSUPLIndex,NAPMEMPLIndex,NAPMINVIndex,NAPMBACKIndex,NAPMEXPTIndex,NAPMIMPTIndex,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
0,1997-03-31 00:00:00,53.1,57.6,58.9,52.1,45.9,41.3,48.5,54.6,53.7,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
1,1997-04-01 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
2,1997-04-02 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
3,1997-04-03 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100
4,1997-04-04 00:00:00,55,58.6,55,53.1,50.8,43.5,51.5,55.7,48.3,...,NaN,1486,1445,NaN,801,21.1,NaN,57.5,118.5,100

三つdfの結合：まずは市場データと経済指標データのDates列の様式をdatetime64に変更し、これで三つdfのこのDates列が一致になり、そしてこの列を基準に三つdfを一つに結合する。新dfの各列は：ｙの値、市場データ、経済指標データの順番

In [17]:
train_df=train_y['Sheet1']
train_mkt_data['Dates']=train_mkt_data['Dates'].astype('datetime64[ns]')
train_ind_data['Dates'] = train_ind_data['Dates'].astype('datetime64[ns]')
train_df = pd.merge(train_df, train_mkt_data, on='Dates')
train_df = pd.merge(train_df, train_ind_data, on='Dates')
train_df

,Dates,dec_rate,signal,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
0,1999-04-01,-0.004176,0,0.007346,-0.001362,0.002121,0.036825,0.001509,0.009022,-0.000526,...,52.7,1799,1720,5.1,881,10.4,NaN,57,133.9,105.7
1,1999-04-02,-0.002029,0,0,0.00573,0.003438,0.002449,-0.001432,0,0,...,52.7,1799,1720,5.1,881,10.4,NaN,57,133.9,105.7
2,1999-04-05,-0.006016,0,0.023604,0.000543,0.009767,0.000611,-0.001207,0,0,...,55.3,1799,1720,5.1,881,10.4,NaN,57,133.9,105.7
3,1999-04-06,-0.008308,0,-0.00225,0.004067,0.00154,0.004274,-0.002569,0.025426,0.010093,...,55.3,1799,1720,5.1,881,10.4,NaN,57,133.9,105.7
4,1999-04-07,0.000000,0,0.006013,-0.00081,0.001919,0.00304,0.006212,-0.008174,-0.000521,...,55.3,1799,1720,5.1,881,10.4,NaN,57,133.9,105.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4627,2016-12-26,-0.000217,0,0,0,0,-0.002066,-0.000467,0,0,...,54,1090,1201,5.61,592,21.5,9,57.6,107.1,98.2
4628,2016-12-27,-0.000683,0,0.000442,-0.001267,-0.000583,0,0,0.002145,0.002994,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
4629,2016-12-28,-0.001023,0,-0.006966,0.003551,-0.000656,0.005694,0.000868,-0.000612,-0.000609,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
4630,2016-12-29,-0.000561,0,-0.000111,0.002401,0.001396,-0.018528,0.002067,-0.002142,0.003353,...,54,1090,1201,5.61,592,21.5,9,57.6,113.7,98.2
4631,2016-12-30,-0.001239,0,-0.003898,0.002774,0.000105,0.001573,-0.000067,0.004906,-0.002734,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2

変更したものを保存する

In [18]:
train_mkt_data.to_csv('train_mkt_data.csv')
train_ind_data.to_csv('train_ind_data.csv')
train_mkt_info.to_csv('train_mkt_info.csv')
train_ind_info.to_csv('train_ind_info.csv')
train_df.to_csv('train_yX.csv',index=False)
'''
説明：
train_mkt_infoは全ての市場インデックスをふくむ
train_ind_infoは全ての経済インデックスを含む
train＿ｙXはtrainデータで、中には日付、dec_rate、各市場データと経済指標データを含む。
'''

'\n説明：\ntrain_mkt_infoは全ての市場インデックスをふくむ\ntrain_ind_infoは全ての経済インデックスを含む\ntrain＿ｙXはtrainデータで、中には日付、dec_rate、各市場データと経済指標データを含む。\n'

validデータの処理

validも指標データの値をdfとして抽出し、字母の指標名を列のインデックスにして、行のインデックスを０からと再設定する

In [19]:
valid_mkt_data=valid_X['市場データ_final'].drop(eliminate_num_list,axis=1)
valid_mkt_data = valid_mkt_data.loc[5:].copy()
valid_mkt_data.columns = list(valid_mkt_data.iloc[0])
valid_mkt_data.drop(index=5, inplace=True)
valid_mkt_data.reset_index(inplace=True, drop=True)
valid_mkt_data.head(5)

,Dates,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,HIIndex,MXEFIndex,...,TRYCurncy,BRLCurncy,COComdty,GCComdty,SIComdty,HGComdty,LBComdty,BDIYindex,XBTCurncy,VIXIndex
0,2017-01-02 00:00:00,0,0,0,0,0,0.005493,0.001949,0,-0.000452,...,3.5441,3.286,0,0,0,0,0,961,1012.35,NaN
1,2017-01-03 00:00:00,0.007267,-0.001383,0.002077,0,0,0.003338,-0.007661,0.007422,0.007611,...,3.5943,3.265,-0.023759,0.008943,0.026268,-0.006586,-0.000911,953,1024.38,12.85
2,2017-01-04 00:00:00,0.005216,0,0.002087,0.027749,-0.001331,-0.000605,-0.000123,-0.001175,0.003466,...,3.5721,3.2213,0.017847,0.00284,0.008715,0.027119,-0.003646,969,1091.66,11.85
3,2017-01-05 00:00:00,0,0.005791,0.003475,-0.006623,0.0008,0,0.002145,0.017422,0.011785,...,3.5932,3.1991,0.007616,0.01373,0.005135,-0.007432,0.002135,983,971.26,11.67
4,2017-01-06 00:00:00,0.003202,-0.00338,-0.000747,-0.005128,0,0.002724,-0.00428,0.00209,-0.000692,...,3.6437,3.2224,0.003691,-0.006688,-0.007093,0.00335,-0.001217,963,898.16,11.32

In [20]:
valid_ind_data = valid_X['経済指標データ_final'].loc[5:].copy()
valid_ind_data.columns = list(valid_ind_data.iloc[0])
valid_ind_data.drop(index=5, inplace=True)
valid_ind_data.reset_index(inplace=True, drop=True)
valid_ind_data.head(5)

,Dates,NAPMPMIIndex,NAPMNEWOIndex,NAPMPRODIndex,NAPMSUPLIndex,NAPMEMPLIndex,NAPMINVIndex,NAPMBACKIndex,NAPMEXPTIndex,NAPMIMPTIndex,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
0,2017-01-02 00:00:00,53.2,53,55,54,51.6,50,48.7,51.8,50.5,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
1,2017-01-03 00:00:00,54.7,60.2,58.7,52.5,53.1,48.5,48.6,56.2,49.8,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
2,2017-01-04 00:00:00,54.7,60.2,58.7,52.5,53.1,48.5,48.6,56.2,49.8,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
3,2017-01-05 00:00:00,54.7,60.2,58.7,52.5,53.1,48.5,48.6,56.2,49.8,...,50,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
4,2017-01-06 00:00:00,54.7,60.2,58.7,52.5,53.1,48.5,48.6,56.2,49.8,...,50,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2

validデータも三つdfを合併する

In [21]:
valid_df = valid_y['Sheet1']
valid_mkt_data['Dates'] = valid_mkt_data['Dates'].astype('datetime64[ns]')
valid_ind_data['Dates'] = valid_ind_data['Dates'].astype('datetime64[ns]')
valid_df = pd.merge(valid_df, valid_mkt_data, on='Dates')
valid_df = pd.merge(valid_df, valid_ind_data, on='Dates')
valid_df

,Dates,dec_rate,signal,ESIndex,TYComdty,TargetPortDailyRtn,NKIndex,JBComdty,VGIndex,RXComdty,...,NAPMNIMPIndex,NHSPSTOTIndex,NHSPATOTIndex,ETSLTOTLIndex,NHSLTOTIndex,OUTFGAFIndex,EMPRGBCIIndex,CHPMINDXIndex,CONCCONFIndex,CONSSENTIndex
0,2017-01-02,-0.001239,0,0,0,0,0,0,0.005493,0.001949,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
1,2017-01-03,-0.000656,0,0.007267,-0.001383,0.002077,0,0,0.003338,-0.007661,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
2,2017-01-04,0.000000,0,0.005216,0,0.002087,0.027749,-0.001331,-0.000605,-0.000123,...,54,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
3,2017-01-05,0.000000,0,0,0.005791,0.003475,-0.006623,0.0008,0,0.002145,...,50,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
4,2017-01-06,0.000000,0,0.003202,-0.00338,-0.000747,-0.005128,0,0.002724,-0.00428,...,50,1090,1201,5.61,592,21.5,9,54.6,113.7,98.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,2022-09-19,-0.027976,1,0.007005,-0.003404,0.00076,0,0,0.004303,-0.000771,...,48.2,1446,1674,4.81,511,-9.9,-1.5,52.2,103.2,58.2
1491,2022-09-20,-0.013651,1,-0.01136,-0.004509,-0.007249,0.003656,-0.000202,-0.011997,-0.013462,...,48.2,1575,1517,4.81,511,-9.9,-1.5,52.2,103.2,58.2
1492,2022-09-21,-0.020086,1,-0.017171,0.003431,-0.00481,-0.012022,-0.00128,0.008384,0.003554,...,48.2,1575,1517,4.8,511,-9.9,-1.5,52.2,103.2,58.2
1493,2022-09-22,-0.024371,1,-0.008998,-0.012994,-0.011396,-0.003319,0.0029,-0.018062,-0.008357,...,48.2,1575,1517,4.8,511,-9.9,-1.5,52.2,103.2,58.2
1494,2022-09-23,-0.030041,0,-0.016702,-0.001109,-0.007346,0,0,-0.023942,-0.003857,...,48.2,1575,1517,4.8,511,-9.9,-1.5,52.2,103.2,58.2

validデータの保存

In [22]:
valid_df.to_csv('valid_yX.csv',index=False)
'''
説明：valid＿ｙXはvalidデータで、中には日付、dec_rate、各市場データと経済指標データを含む。
'''

'\n説明：valid＿ｙXはvalidデータで、中には日付、dec_rate、各市場データと経済指標データを含む。\n'

In [23]:
valid_mkt_data.to_csv('valid_mkt_data.csv')
valid_ind_data.to_csv('valid_ind_data.csv')